### ISSUE TITLE
question: iptvnator-backend

### ISSUE THREAD

**Issue by bendschs** [4gray/iptvnator-backend#1]
What exactly is the backend for? i figured i can also play channels when it is not even running, as long as the frontend is up, everything works as expected.

**Comment by 4gray** [comment]
The backend is needed to fetch and update playlists via URL because of [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) policy in the browser. It will also be used by PWA app to fetch the EPG hopefully in the near future.

**Comment by bendschs** [comment]
allright, got it. thanx for the reply!
